---
title: "Covid91 vaccine study Final2023"
author: "April Parry"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "7/31/2023" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="final.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
FinalData$treatment <- relevel(FinalData$treatment,ref="placebo")
#FinalData$infected <- relevel(FinalData$infected,ref="OK")
Male = filter(FinalData, sex =="M")
Female = filter(FinalData, sex =="F")
LGBTQ= filter(FinalData, LGBTQ =="gay")
Druguser = filter(FinalData, DrugUser =="yes")
```

# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

#Method
the method here is  to change the data in this final data so that we can factor variables then arrange the ones who were treated with the placebo and the vaccine and the others who are infected with covid and see the differences betwwen the males, females, LGBTQ's and drugusers.  

## Males


## Females


## LGBTQ



## Druggies


# Overall Results and Conclusions